components:
  schemas:
    AddRequest:
      type: string
    AddResponse:
      type: string
    SubtractRequest:
      type: string
    SubtractResponse:
      type: string
    a:
      type: string
    b:
      type: string
    result:
      type: string
  securitySchemes: {}
info:
  contact:
    name: API Support
  description: Simple Calculator Web Service
  title: CalculatorService
  version: 1.0.0
openapi: 3.0.0
paths:
  /Add:
    post:
      description: Add two numbers
      operationId: Add
      parameters:
      - description: SOAP Action header
        in: header
        name: SOAPAction
        required: false
        schema:
          type: string
      - description: Content type
        in: header
        name: Content-Type
        required: true
        schema:
          default: text/xml
          enum:
          - text/xml
          - application/soap+xml
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                parameters:
                  type: string
              required:
              - parameters
              type: object
          application/soap+xml:
            schema:
              example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <soap:Header>\n\
                \        <!-- Optional SOAP headers -->\n    </soap:Header>\n    <soap:Body>\n\
                \        <Add xmlns=\"http://example.com/service\">\n            <!--\
                \ Request parameters -->\n        </Add>\n    </soap:Body>\n</soap:Envelope>"
              type: string
          text/xml:
            schema:
              example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <soap:Header>\n\
                \        <!-- Optional SOAP headers -->\n    </soap:Header>\n    <soap:Body>\n\
                \        <Add xmlns=\"http://example.com/service\">\n            <!--\
                \ Request parameters -->\n        </Add>\n    </soap:Body>\n</soap:Envelope>"
              type: string
        description: SOAP request body
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  parameters:
                    type: string
                type: object
            text/xml:
              schema:
                example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                  \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  \
                  \  <soap:Body>\n        <AddResponse xmlns=\"http://example.com/service\"\
                  >\n            <!-- Response data -->\n        </AddResponse>\n\
                  \    </soap:Body>\n</soap:Envelope>"
                type: string
          description: Successful SOAP response
        '500':
          content:
            text/xml:
              schema:
                example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                  \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  \
                  \  <soap:Body>\n        <soap:Fault>\n            <faultcode>soap:Server</faultcode>\n\
                  \            <faultstring>Server Error</faultstring>\n         \
                  \   <detail>\n                <!-- Fault details -->\n         \
                  \   </detail>\n        </soap:Fault>\n    </soap:Body>\n</soap:Envelope>"
                type: string
          description: SOAP Fault
      summary: Add
      tags:
      - SOAP Operations
  /Subtract:
    post:
      description: Subtract two numbers
      operationId: Subtract
      parameters:
      - description: SOAP Action header
        in: header
        name: SOAPAction
        required: false
        schema:
          type: string
      - description: Content type
        in: header
        name: Content-Type
        required: true
        schema:
          default: text/xml
          enum:
          - text/xml
          - application/soap+xml
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                parameters:
                  type: string
              required:
              - parameters
              type: object
          application/soap+xml:
            schema:
              example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <soap:Header>\n\
                \        <!-- Optional SOAP headers -->\n    </soap:Header>\n    <soap:Body>\n\
                \        <Subtract xmlns=\"http://example.com/service\">\n       \
                \     <!-- Request parameters -->\n        </Subtract>\n    </soap:Body>\n\
                </soap:Envelope>"
              type: string
          text/xml:
            schema:
              example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <soap:Header>\n\
                \        <!-- Optional SOAP headers -->\n    </soap:Header>\n    <soap:Body>\n\
                \        <Subtract xmlns=\"http://example.com/service\">\n       \
                \     <!-- Request parameters -->\n        </Subtract>\n    </soap:Body>\n\
                </soap:Envelope>"
              type: string
        description: SOAP request body
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  parameters:
                    type: string
                type: object
            text/xml:
              schema:
                example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                  \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  \
                  \  <soap:Body>\n        <SubtractResponse xmlns=\"http://example.com/service\"\
                  >\n            <!-- Response data -->\n        </SubtractResponse>\n\
                  \    </soap:Body>\n</soap:Envelope>"
                type: string
          description: Successful SOAP response
        '500':
          content:
            text/xml:
              schema:
                example: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope\
                  \ xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  \
                  \  <soap:Body>\n        <soap:Fault>\n            <faultcode>soap:Server</faultcode>\n\
                  \            <faultstring>Server Error</faultstring>\n         \
                  \   <detail>\n                <!-- Fault details -->\n         \
                  \   </detail>\n        </soap:Fault>\n    </soap:Body>\n</soap:Envelope>"
                type: string
          description: SOAP Fault
      summary: Subtract
      tags:
      - SOAP Operations
servers:
- description: SOAP Service Endpoint
  url: http://example.com
tags:
- description: SOAP web service operations
  name: SOAP Operations
